#!/bin/bash

# called by mon1 or topscrn, show in xterm window or text console without getting too wide - useful with zfs
# Save to /usr/local/bin

# Hides some fields and sorts on field 3 (free space)
df -T -h |grep -v tmpfs |awk '{$1="";$3=""; print}' |column -t |sort -h -k 3
