#!/bin/bash

# called by mon1, show in xterm window without getting too wide
# Save to /usr/local/bin

# Hides some fields and sorts on field 3
df -T -h |grep -v tmpfs |awk '{$1="";$3=""; print}' |column -t |sort -h -k 3
