---
- name: Fix debian-derived servers so users in sudo group can do sudo commands with nopass for ansible ctrl
  hosts: '{{target}}'
  become: yes
  tasks:
    - name: Uncomment %sudo nopasswd line
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^#\s%sudo\s+ALL.*NOPASSWD.*'
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: 'visudo -cf %s'

    - name: Add dave to sudo group to enable nopass
      ansible.builtin.user:
        name: dave
        groups: sudo
        append: yes
