---
- name: Reset local user password - requests interactive input
  hosts: '{{target}}'
  become: yes
  gather_facts: no

  vars_prompt:
    - name: "plain_password"
      prompt: "Enter the new password for the user:"
      private: yes # hides input

    - vars:
        target_user: "root" # EDITME

    - tasks:
        - name: "{{ target_user }}"
          password: "{{ plain_password | password_hash('sha512') }}"
          update_password: always


